# Site settings
title: "Addy Wiki"
description: >
  Official documentations for Addy

author: Addy
email: addy-org@googlegroups.com
twitter_username: addy_org
github_username: addy-org
gitter_username: addy-org

baseurl: "/Wiki" 
url: "https://addy-org.github.io"

google_analytics_id: UA-96193556-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
collections:
  documentation:
    output: true
    permalink: /:name/

permalink: /:title/

sass:
    style: compressed

exclude: [vendor]
